//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public int IdАгента { get; set; }
        public string Тип_агента { get; set; }
        public string Наименование_агента { get; set; }
        public string Электроннаяпочтаагента { get; set; }
        public string Телефонагента { get; set; }
        public string Логотип_агента { get; set; }
        public string Юридический_адрес { get; set; }
        public Nullable<double> Приоритет { get; set; }
        public string Директор { get; set; }
        public Nullable<double> ИНН { get; set; }
        public double КПП { get; set; }
        public Nullable<int> IdПродукции { get; set; }
    
        public virtual ProductSale ProductSale { get; set; }
    }
}
