//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsShort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductsShort()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int IdПродукции { get; set; }
        public string Наименование_продукции { get; set; }
        public string C_Тип_продукции { get; set; }
        public Nullable<double> C_Артикул { get; set; }
        public Nullable<double> C_Количество_человек_для_производства { get; set; }
        public Nullable<double> C_Номер_цеха_производства { get; set; }
        public string C_Минимальная_цена_для_агента { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
