//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSale()
        {
            this.Agents = new HashSet<Agents>();
        }
    
        public int IdПродавПродукц { get; set; }
        public string Продукция { get; set; }
        public string Наименование_агента { get; set; }
        public Nullable<System.DateTime> Дата_реализации { get; set; }
        public Nullable<double> Количество_продукции { get; set; }
        public Nullable<int> IdПродукции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ProductsShort ProductsShort { get; set; }
    }
}
